services:
  redis:
    container_name: cache
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    hostname: ${REDIS_HOST}
    volumes:
      - redis:/data
    env_file:
      - .env

volumes:
  redis:
    driver: local
